networks:
  localnet:
    name: localnet
    external: true

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: app-go
    ports:
      - 3000:3000
    depends_on:
      - surrealdb
    networks:
      - localnet

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: unless-stopped
    ports:
      - 8000:8000
    command: ${SURREAL_COMMAND}
    volumes:
      - ${PWD}/surrealdb:/var/lib/surrealdb
    networks:
      - localnet
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          memory: 1G
